### ISSUE TITLE
Tagging God, Christ, and the Devil as named entities

### ISSUE THREAD

**Issue by scottkleinman** [scottkleinman/aeme#47]
Should we be using `<name type="person">` for God, the various forms of Christ, and the Devil? I've done it for one short text, but it's potentially a lot of tagging for longer texts.

**Comment by mmwwah** [comment]
To follow up on this, I've got God, Christ, and Holy Ghost `#bio` nametags.  How far do we want to take the interpretation, in terms of kennings and euphemisms?  I've been tagging the phrase "goddess lamb" (which Orm looooooves) with God but not with Christ, because that seems like an interpretation too far.  But I've just hit a section where he uses "Faderr" a lot, clearly meaning God the Father.  Tag with God or leave it be? 

I'm just looking for opinions here -- this isn't a cri de coeur.

**Comment by scottkleinman** [comment]
I think we discussed this in issue #79. Should we close this issue too?

**Comment by mmwwah** [comment]
Oof, I forgot we'd discussed it.  I'll close this one too.  Thanks.
