### ISSUE TITLE
stacked letters

### ISSUE THREAD

**Issue by mmwwah** [scottkleinman/aeme#52]
Orm likes to stack his double letters -- not as subsequent additions (ie, not in different ink, as he rethinks his ormography) but as a space-saving device.  Like so:
![screen shot 2015-06-16 at 10 53 41](https://cloud.githubusercontent.com/assets/7809545/8186100/3d2a89f8-1416-11e5-9d30-068bf678d003.png)

Is there a set way to encode that?  I've skimmed MUFI and didn't see anything.  Do we need to create a new tag, or use Gaiji, or...?

[I hope that image displays correctly.  If not, I'll try again.]

**Comment by scottkleinman** [comment]
My flight's delayed, so I have some time to answer this. In the [MUFI recommendations](http://folk.uib.no/hnooh/mufi/specs/MUFI-Alphabetic-3-0.pdf), search for `&sup;` and `&nsup;`. These should do the trick.

That does not encode the *reason* for Orm's use of the stacked letters. You could perhaps take the reason as "inferred", since encoding like `n<add place="supralinear">n</add>` would indicate that the second "n" was a later addition. If you wanted to encode the fact that the letter is written to save space, perhaps you would have to use `<hi>` and invent an attribute much as we did with `@ln` for *litterae notabiliores* in `<sg/>`.

**Comment by mmwwah** [comment]
Yes, Zach played with <&sup> and then ended up using <hi> as a placeholder.  I'm thinking that attribute invention may be the way to go.

**Comment by scottkleinman** [comment]
What about `<hi type="space-saver">&nsup;</hi>`? I'm not saying that you should use "space-saver", but something informative like that. Keep in mind that you're probably encoding something that we may not be able to render in the UI unless we build it in (which in this case would probably not be technically difficult). So there is an issue of whether it is worth doing.

**Comment by skgoetz** [comment]
Is it totally regular, or are there times at which doublets aren't stacked? If non-stacking is rare, you could also declare it editorially (in prose, to the reader) and not encode it. (I am feeling around for whether Meg would prefer to encode it, to encode and represent it, etc.)

I'd caution against `<add>` in this case because it's not added subsequently.

**Comment by skgoetz** [comment]
p.s. Meg, to get tags to display, enclose them in grave accent marks, the one that's usually above tab on a standard-size keyboard.

**Comment by zabt** [comment]
The regularity of stacking doublets depends a lot on the letter.  For example, an n will almost always be stacked whereas a d never and a t about 50/50.

**Comment by scottkleinman** [comment]
I wonder, then if it is even necessary to use `<hi>`? You could just use the combining character. At the end, it would be possible to turn Zach's estimate into hard counts and supply an editorial comment in the teiHeader. If individual lines look like they are unusual (e.g. Orm broke his pattern of never stacking "d" in order to save space), that could be placed in an editorial note for individual lines.
