### ISSUE TITLE
MUFI PUA characters

### ISSUE THREAD

**Issue by mmwwah** [scottkleinman/aeme#56]
Are we cool with using the MUFI "private use area" characters?  I hope so, because Orm uses a bunch of them.

Also, should I be adding to entities.dtd as I deploy them?

Finally, I assume that there are some macron abbreviations for n/m in the SEL.  Are we using the macron (00AF), which seems to be combining [unless I misunderstand MUFI] or the combining macron (0304) for them?

**Comment by scottkleinman** [comment]
Policy is to avoid PUA characters if possible, but that may be difficult for Ormulum. They will render if we use Junicode as our font--which is what we are planning.

Adding them to entities.dtd is for convenience. `&combmacr;` is in there because I find it easier to type than the code point. Feel free to do the same, but we can always use search and replace later. The Unicode code point is always good; it's just hard to read.

That should answer your last question. I have been using the combining macron.

**Comment by mmwwah** [comment]
Yeah, I don't think we can avoid PUAs for the Ormulum.  He makes abundant, and meaningful, use of enlarged lower-case letters, for example.  

I far prefer to type than to code-point (if that's a verb) too.  So it's cool to add things that aren't already in entities.dtd and then do a search and replace on Zach's code (which uses the code point exclusively)?

**Comment by mmwwah** [comment]
Never did get an answer on this, and I'm getting back to AEME today.  Is it okay to add things to entities.dtd?  Do I need to do a pull request in order to get my changes approved and thus committed and functioning, or will it work for me right off?

(Sorry to be clueless about the flow -- I'm still figuring things out.)

**Comment by scottkleinman** [comment]
The short answer is that you should just push changes/additions to the `entities.dtd` file in the `junius1` folder. You don't need to do a pull request.

The longer answer is that `entities.dtd` exists as a separate file primarily so that you don't have to scroll down to the beginning of the `<text>` element each time you want to edit. If you look at the top, you'll see that the `<teiHeader>` is actually an entity. Additionally, should you decided to break the text into separate files during the editing process (as is necessary for Laud Misc. 108), you can use the same entities file for all of them. However, since the `entities.dtd` file contains a reference to the `<teiHeader>`, which is specific to the manuscript, it doesn't make sense to use the same entities file for both manuscripts. In the future, we could remove the `<teiHeader>` and then combine the files for each manuscript into the "project" `entities.dtd` file if that seems advisable. But that would be near the end of the project.

**Comment by mmwwah** [comment]
Short answer: Great -- thanks!

Long answer: That makes perfect sense -- thanks!
