### ISSUE TITLE
file structure/planning

### ISSUE THREAD

**Issue by mmwwah** [scottkleinman/aeme#58]
I realize that Zach has created xml files according to Holt & White's textual divisions (dedication; preface; texts; etc.).  I should have dealt with this a lot sooner, but in any case, I'm dealing with it now.  I just want to check with y'all before I give him instructions.  I know that Laud 108 is organized by text (Havelok, St Blaise, etc), but is that our plan for Junius 1 too?  I ask this because there is disagreement about H&W's division of the frontmatter; some scholars believe they imposed divisions where Orm intended none.  

I don't really understand the UI well enough to make good decisions on file structure.

**Comment by scottkleinman** [comment]
For the most part, Laud Misc. 108 has structural "dividers" (e.g. rubrics or other indicators) that coincide with our modern sense the beginnings and endings of "texts". So it's pretty easy to deal with. But you may not feel the same about the structure of Junius 1, so you don't have to take Laud Misc. 108 as a model.

If you disagree with Holt and White's edition, you should definitely go with your own editorial interpretation (critical debate can go in the explanatory material). But I think you are asking a technical question about how it will be rendered. The basic division we have between critical and diplomatic views in the interface may cover some of what you want to address. If there is no indicator of a division in the MS, the diplomatic view won't show one. You may choose to show one (Holt & White's or your own) in the critical view, since either will be a critical intervention, in which case you need to have it encoded somehow. I think you'll have to give us a specific example to comment on how. 

In part, this territory may be covered by `@resp`, but this is mainly good for reading the markup. Designing a viewer that renders allows you use this attribute to toggle between H&W and Worley, for instance, becomes theoretically possible, but it would possibly be an extension of the initial AEME interface.

**Comment by mmwwah** [comment]
A couple of responses here:
1. When I framed the question, I was thinking not of rendering but of file structure -- one big file or separate files for the textual divisions (and if so, then H&W's or Worley's?).  I'm now thinking that all of Junius 1 belongs in two files: frontmatter and homilies.  That is crystal clear in the text, and users can deal with any subdivisions on their own (with help/info via notes).  What say ye?  

2. You (indirectly) raise a question about lineation, but I realize it would be better as a separate issue.  Stay tuned.

**Comment by scottkleinman** [comment]
Your two files idea is definitely doable for the editing stage, though you may want to merge them for the final product (the idea being a goal of one file per manuscript). But if you split the text into two files at this stage, make sure you copy the following into both files:

```xml
<!DOCTYPE TEI SYSTEM "entities.dtd">
<TEI xml:id="laudmisc108" xmlns="http://www.tei-c.org/ns/1.0">
  <!-- Standoff <teiHeader> and <facsimile> files --> &teiHeader; &facsimile;
  <!-- End of Standoff <teiHeader> and <facsimile> files -->
```
Otherwise, the `<teiHeader>` and `<facsimile>` elements won't get included and the files won't validate.

**Comment by mmwwah** [comment]
Ah, okay.  Right now we've got four files: Zach created separate ones for each of H&W's divisions in the frontmatter plus one for the homilies themselves.

Merge now or merge later?

**Comment by scottkleinman** [comment]
I think this is just a matter of what is more convenient for your workflow.

**Comment by mmwwah** [comment]
Okay, cool.  Later it is!
