### ISSUE TITLE
stacked wynn

### ISSUE THREAD

**Issue by mmwwah** [scottkleinman/aeme#60]
As you know, Orm's frenzy for geminates has him stacking double letters quite often.  He has a particular way to stack wynns, which is really more doubling the lobe than stacking them, so that it forms a single character.  It looks like this:
![screen shot 2015-10-29 at 18 06 26](https://cloud.githubusercontent.com/assets/7809545/10833476/89302de6-7e68-11e5-824b-7a964bfbae5b.png)

I don't see anything like it in MUFI.  And I hesitate to encode it as we've been doing the other stacked letters, ie, `<hi>r</hi>` (for stacked "r"s), since it's a single character.

Thoughts?

**Comment by scottkleinman** [comment]
I think you need to use the [Gaiji](http://www.tei-c.org/release/doc/tei-p5-doc/en/html/WD.html) module for this.

In the `<encodingDesc>` section of the `<teiHeader>`, add

```xml
<charDecl>
 <char xml:id="wynnsup">
  <charName>COMBINING LATIN SMALL LETTER WYNN</charName>
  <charProp>
   <localName>entity</localName>
   <value canonical-combining-class="214">wynnsup</value>
  </charProp>
  <figure>
   <graphic url="wynnsup_img.png"/> <!-- Add a url to your image here. -->
  </figure>
  <mapping type="diplomatic">&#F03C;</mapping> <!-- MUFI &wsup; -->
  <mapping type="critical">w</mapping>
 </char>
</charDecl>
```

I can't see the entire word in your example, but I'm going to assume that the word is *owwen*. So, in the body of the text, this would be encoded

```xml
ow<g ref="#wynnsup">w</g>en
```

You can make this a little easier by adding the following to `entities.dtd`:

```xml
<!ENTITY wynnsup '<g ref="#wynnsup">w</g>' >
```

Then you can use the following in the body of your text:

```xml
ow&wynnsup;en
```
Just a couple of further comments. I have followed MUFI conventions in naming the glyph "COMBINING LATIN SMALL LETTER WYNN" and the entity representation "wynnsup" (based on "wsup", which is "COMBINING LATIN SMALL LETTER W". I've then mapped that the one on to the other so that the glyph will appear with the second "w" above the first. However, `&wsup;` is a Private Use Area character, so this will only work in the Junicode font.

It might be easier just to use `&wsup;` if all wynns map on to "w" in the text. Printing wynn would then be reserved for the future facsimile view...

**Comment by mmwwah** [comment]
I'm inclined to, as you say, use `&wsup;`, just because the COMBINING LATIN SMALL LETTER W isn't found anywhere in the ms.  But can we map "wsup" onto something like this double-barreled wynn for the diplomatic rendering?

**Comment by scottkleinman** [comment]
You could do this in the entities declaration. I think you would need something like `&combwynn;` (COMBINING WYNN) as your alias and map it to `&#xF03C;`. I'm a little uneasy about this, as we may end up changing these aliases to code points later on. Also, we're trying to stick to MUFI standards as much as possible and `&#xF03C;` also has a standard name. Probably the way to solve this is to modify the  `<charDecl>` I proposed earlier:
```xml
<charDecl>
 <char xml:id="wsup">
  <charName>COMBINING LATIN SMALL LETTER WYNN</charName>
  <charProp>
   <localName>entity</localName>
   <value canonical-combining-class="214">wsup</value>
  </charProp>
  <figure>
   <graphic url="wynnsup_img.png"/> <!-- Add a url to your image here. -->
  </figure>
  <mapping type="diplomatic">&#xF03C;</mapping> <!-- MUFI &wsup; -->
  <mapping type="critical">w</mapping>
 </char>
</charDecl>
```
Now you (the human) know that `&wsup;` is a COMBINING LATIN SMALL LETTER WYNN mapped to the MUFI code point for COMBINING LATIN SMALL LETTER W in the diplomatic markup. Now you tell the xml parser in the `entities.dtd` file:

```xml
<!ENTITY wsup '<g ref="#wsup">w</g>' >
```
And you can then use the encoding `&wsup;` everywhere in the body of your text. Does that make sense?

**Comment by mmwwah** [comment]
I didn't respond to this earlier because I hadn't quite got my head round it.  Now I think I have, but it raises a couple of other questions.

1. I think my head is going to be screwed on straighter if I work my way through the Junius 1 `tei-header.xml` file line by line.  Until then, I feel drugged and confused.  I will probably do that next and pester you with questions as I go.

2. It's best if we come to an agreement about Orm's stacked geminates sooner rather than later.  I think it's important to preserve them in the DipV, because the utility of the AEME Ormulum won't just be the orthography -- it will be the paleography.  (I'm ready to make this a sales point for future grants.)  He loves his stacked geminates, and I'll need to figure out the encoding for probably a dozen different letters (my count is still partial).  Obviously we'll have to use the Gaiji model, but is there some way we can streamline the stack-factor, so that a scholar could find all the stacked consonants and not search for them letter by letter?

**Comment by scottkleinman** [comment]
I think one way to do this would be to add the word "STACKED" somewhere in the `<charName>` element. Then you can generate a list of all the characters with "STACKED" and then search for all the entities equivalent to those characters. There may be more efficient methods though, so I'll think about this.

**Comment by mmwwah** [comment]
Sounds good.  I'm going to use (and entitize) `&wsup` for now, and we can deal with it further later.

We're going to have the same issue with the double-lobed thorn (just like the double wynn above but with an ascender).  For now I'm going to use `&ethsup`.

Hey, what's the difference between `&urrot` and `&rrotsup`?  They look identical to me.  I've been using the former, but should I be using the latter?

**Comment by scottkleinman** [comment]
`&urrot;` = COMBINING ABBREVIATION MARK SUPERSCRIPT UR ROUND R FORM 
`&rrotsup;` = COMBINING LATIN SMALL LETTER R ROTUNDA

Presumably, the former should only be used for an abbreviation of "ur".

**Comment by mmwwah** [comment]
They look identical though, right?

Orm uses that mark to abbreviate both "er" and "ur."  Same glyph.  Does this mean that we need to hand-code `<choice>`s for each one, to display in the CritV?  There is no `&errot;`.

**Comment by scottkleinman** [comment]
Somewhere back in the mists of time, Sharon made a point about this, but I'm not sure where. It was probably in discussions of abbreviations or the Gaiji module. In any event, if Orm uses the same glyph for "er" and "er", I would use the same glyph. Since this is an abbreviation, you'll be using `<choice>` anyway to expand it. In `<reg>`, you can just put `<ex>er</ex>` or `<ex>ur</ex>`, as appropriate. At least, that's the way I have been doing it. Implicitly, Orm the same abbreviation marker for both. Down the line, you might want to use Gaiji for the diplomatic view. For instance `<orig><am><g ref="#er">&rrotsup;</g></am></orig>` v. `<orig><am><g ref="#ur">&rrotsup;</g></am></orig>`. Then you've made it explicit that Orm uses the same abbreviation marker with two values. None of this will change the output; it's only useful for searching.

**Comment by mmwwah** [comment]
Okay, great.  Thanks.
