### ISSUE TITLE
Save It For Laters

### ISSUE THREAD

**Issue by mmwwah** [scottkleinman/aeme#61]
These are the things in the Guidelines that I am assuming I don't need to worry about right now, but I'm Issuing for confirmation before I blunder onward:

• A well-formed header?  Right now I've got a kind of placeholder that Zach put together using the Guidelines.  When I look at Mary of Egypt (which you'd pointed me toward as a good example), I see pointers to other files but not a fully elaborated header.  If I should take care of the header now, let me know.

• `<collection>` values?  They're mentioned in the Guidelines, but I don't see any evidence of them on the ground.

• `<facsimile>`?

• global list of scribal hands?

• Locus values?  Junius 1/Ormulum isn't mentioned in DIMEV, and I'm assuming locus values apply only to DIMEV, not to anything else.  Correct me if I'm wrong.

**Comment by scottkleinman** [comment]
Your files should have a link to well-formed and valid `<teiHeader>` and `<facsimile>` elements, but this is mainly for the purpose of validating your encoding of the text. The information is incomplete in the `<teiHeader>`, so you'll want to add material; but when you choose to do that in the process is up to you. For Oxford, Bodleian Library, Junius 1, "junius" is the `<collection>` value. See [`msIdentifier`](http://scottkleinman.net/wp-content/uploads/guidelines-4.0/The_teiHeader_Section/fileDesc/sourceDesc/msDesc/msIdentifier).

There is currently no global list of scribal hands, so define them for Junius 1 in the `<teiHeader>`.

If usage for an element/attribute is not defined in the AEME Guidelines, you are by default referred to the TEI Guidelines. That's the case for [`<locus>`](http://www.tei-c.org/release/doc/tei-p5-doc/en/html/ref-locus.html). Let me know if that clears up your question about DIMEV.

The `<facsimile>` element is required by the schema, so it is included at the top of the file. However, we're not encoding it yet because we're exploring IIIF annotation as a means of handling facsimile markup.

**Comment by mmwwah** [comment]
I guess I don't understand how the Standoff headers work in Mary of Egypt.

Here's what we've got for the moment, and it seems to validate okay.  Is it okay to proceed with it as is?  (Leaving aside the `<hi>` line Zach put in, that is)
`<?xml version="1.0" encoding="UTF-8"?>
<?xml-model href="http://www.tei-c.org/release/xml/tei/custom/schema/relaxng/tei_all.rng" type="application/xml" schematypens="http://relaxng.org/ns/structure/1.0"?>
<?xml-model href="http://www.tei-c.org/release/xml/tei/custom/schema/relaxng/tei_all.rng" type="application/xml"
	schematypens="http://purl.oclc.org/dsdl/schematron"?>
<TEI xmlns="http://www.tei-c.org/ns/1.0">

  <teiHeader>
      <fileDesc>
         <titleStmt>
            <title></title>
         </titleStmt>
         <publicationStmt>
            <p></p>
         </publicationStmt>
         <sourceDesc>
            <p></p>
         </sourceDesc>
      </fileDesc>
      <encodingDesc>
         
         <tagsDecl>
            <namespace name="junius1">
               <tagUsage gi="hi" render="superscript"></tagUsage>
            </namespace>
         </tagsDecl>
      </encodingDesc>
  </teiHeader>
   <text>
      
    
      <body xml:id="junius1">`

Re `<collection>`, I was referring to p. 3 of the Guidelines which mention a table of equivalents.  Is that around somewhere, or is that a Save It For Later?

I'm not entirely clear on how `<locus>` differs from `<anchor>`, but I can at least tell that I don't need to worry about it.  For now.  And I'm happy to see that `<facsimile>` is likewise a Not Now.

**Comment by scottkleinman** [comment]
Some quick comments. When you're pasting in blocks of code, use three ticks followed by xml like this:

\`\`\`xml
&lt;someCode&gt;&lt;/someCode&gt;
\`\`\`

I just saw a blank space before I figured out that you had used single ticks.

In your code, you have the following line twice:

```xml
<?xml-model href="http://www.tei-c.org/release/xml/tei/custom/schema/relaxng/tei_all.rng" type="application/xml" schematypens="http://relaxng.org/ns/structure/1.0"?>
```
The repetition aside, this doesn't include the AEME schema. Here's the code from the Mary of Egypt file with some explanations:

```xml
<?xml version="1.0" encoding="UTF-8"?><?oxygen RNGSchema="http://www.emesoc.org/schema/aeme.rng" type="xml"?>
<!DOCTYPE TEI SYSTEM "entities.dtd">
<TEI xml:id="laudmisc108" xmlns="http://www.tei-c.org/ns/1.0">
    <!-- Standoff <teiHeader> and <facsimile> files --> &teiHeader; &facsimile;
    <!-- End of Standoff <teiHeader> and <facsimile> files -->
    <text>
```
* Line 1 contains the xml declaration and includes the AEME schema from the EMESoc website.
* Line 2 includes the `entities.dtd` file. Since there is no path given, the file must be in the same folder as the file you are working in, but you can change that.

Inside the `entities.dtd` file you can see this:

```xml
<!ENTITY teiHeader SYSTEM "teiHeader.xml">
<!ENTITY facsimile SYSTEM "facsimile.xml">
```
This creates aliases for the `teiHeader.xml` and `facsimile.xml` files. Again, there's no path given, so the files must be in the same folder.

* Line 3 starts the `<TEI>` root element.
* Line 4 uses the entity representation aliases to include the `teiHeader.xml` and `facsimile.xml` files.

This way, oXygen will validate the entire contents of the `<TEI>` element, but you don't need to scroll past long `<teiHeader>` and `<facsimile>` elements in order to begin working on the text.

I think the main difference between `<locus>` and `<anchor>` is that the latter is actually `<anchor/>`, meaning that it does not require any content. So look at the following code:

```xml
<locus>f. 1r</locus>
<l>Whan that Aprill with his shou<anchor xml:id="randomAnchor"/>res soote</l>
```
An anchor can go anywhere, but `<locus>` can only be used to tag content that is semantically a location. It doesn't even need to be a location in the text. So you could do something like `"This phrase in the Ormulum also begins at <locus>the beginning of Beowulf</locus>."` (Wouldn't that be a discovery! And now it's on the internet!)

**Comment by mmwwah** [comment]
Thanks *very* much for the header explanation -- very clear, very helpful.  Didn't know about three ticks.

Locus vs anchor: Got it.  (And hurray for the Internet, source of all things!)

**Comment by mmwwah** [comment]
Related, since you brought up entities.dtd.  I've been adding the MUFI characters we need to our entities.dtd file, so that's all good.  We don't also need to declare them as a subset under `<!DOCTYPE>` in the header, do we?  (p. 6 of Guidelines)
