### ISSUE TITLE
paragraph break

### ISSUE THREAD

**Issue by mmwwah** [scottkleinman/aeme#73]
Can `<p>` be a `<choice>`?  In other words, do I *have* to use a `<p>` whenever Orm uses a `&#parag;` (his runic pilcrow), or can I (as I prefer) have it encoded as a paragraph break in the CritV but not in the DipV?

**Comment by scottkleinman** [comment]
`<p>` should only be used for prose (see [here](http://scottkleinman.net/wp-content/uploads/guidelines-4.0/The_text_Section/body/Higher_Block-Level_Structural_Elements/p)). We may or may not choose to render the pilcrow in the critical view.

If you have a pilcrow in a verse line, the default behaviour is for `<l>` to trigger a line break in exactly the way that `<p>` does. Since the Ormulum is written out as prose, we will be "undoing" this behaviour in the style sheet. That means that, if you *want* line breaks to appear, you have to use `<lb/>` or perhaps enclose groups of lines in `<lg>`, which will trigger a line break. But the pilcrow glyph is essentially independent of markup indicating structure or layout.

**Comment by mmwwah** [comment]
Great.  That answer pleases me.  Thanks!
