### ISSUE TITLE
vertical insertions

### ISSUE THREAD

**Issue by mmwwah** [scottkleinman/aeme#80]
IIRC, we have discussed this in a desultory fashion, but we didn't decide on anything firm (correct me if I'm wrong).  I've hit the first vertical insertion Orm makes, to wit:
![screen shot 2015-11-17 at 20 01 10](https://cloud.githubusercontent.com/assets/7809545/11229728/6d923dce-8d66-11e5-801c-96a9fb83af10.png)

As you can see, the lettering is smaller and doesn't line up with the body-of-text lines.  And it's vertical.

I'm assuming that the insertion line only needs to be dealt with in the FacsV, but the inserted text certainly needs to be in the DipV and the CritV.  And I'm assuming that the tie sign, and the fact that the text is inserted a posteriori, belong in the DipV.

I've read the TEI section "Vertical Orientation in Horizontal Scripts," so I see a light at the end of the tunnel, but I'm not ready to steer the locomotive.  How should I be handling these?  There are only going to be more as I go along.

**Comment by scottkleinman** [comment]
I can't see from the context where "mann" should go, but I'll assume it's before "witenn". So, in this case, you would have something like:

```
wile <metamark rend="line" function="connector" target="#mann01"> 
<add xml:id="mann01" place="marginRight>mann</add> witenn ...
```
(Obviously, I'm not encoding some of the other features of the text here, and I'm leaving the verticality for the facsimile view).

The result will read "wile mann witenn" in both the critical and diplomatic views. However, if we choose to style additions (e.g. turn them pink), that will only appear in the diplomatic view.

As a separate issue, it looks like this addition might actually be in the gutter between two columns, rather than in the margin. The AEME schema does not have a way of describing this, and `@place` takes only a limited number of values (the file will not validate if you use `@place="gutterRight"`). For now, I recommend something like this `<add place="marginRight" rend="gutter">`. That way the file will validate, and you can find these examples later if you need to change them. I would sort of like to collaborate with SEENET on something like this to decide on a convention that can be adopted widely, as it's sure to be an issue encountered elsewhere.

**Comment by mmwwah** [comment]
Excellent -- thanks.  So, do I need to encode Orm's complex system of tie signs?  I see that an `xml:id` is serving the locator purpose in the encoding.  Is that something that belongs only in the FacsV?

In this case, the addition is in the margin, but there are others in the gutter, and I will do as you suggest for those.

Thanks.

**Comment by scottkleinman** [comment]
`@function` allows any value, so you could develop a taxonomy for describing the tie signs in `<metamark>`. You could also define an `@xml:id` for the type of metamark in the appropriate part of the teiHeader, giving it a more elaborate description, and then refer to it using `@corresp`. I'm not wild about that option though.
