### ISSUE TITLE
Schema does not allow `gap@reason`

### ISSUE THREAD

**Issue by scottkleinman** [scottkleinman/aeme#84]
This may apply to other attributes listed at [http://scottkleinman.net/wp-content/uploads/guidelines-4.0/The_text_Section/Unclear_or_Illegible_Characters](http://scottkleinman.net/wp-content/uploads/guidelines-4.0/The_text_Section/Unclear_or_Illegible_Characters).

This bug was raised in issue #83.

**Comment by skgoetz** [comment]
Hi! On it--wait a bit.

**Comment by skgoetz** [comment]
I would like an example, possibly a screen shot, from @mmwwah or @scottkleinman. 

`<gap` is a core element, and `@reason` is on it by default. (The delay is so that I could check my possibly faulty memory against [P5 core](http://www.tei-c.org/release/doc/tei-p5-doc/en/html/ref-gap.html). I've loaded the 0.3.5 customization file in Roma, and it confirms that `gap[@reason]` is available. In junius1.xml straight from GitHub, I am able to insert `gap` in a random `p` and assign a `@reason`. Please clarify the bug report.

I've fixed an unrelated oversight in entities.dtd while glancing over junius1.xml.

**Comment by skgoetz** [comment]
After rereading #83, I suppose I'm asking only @scottkleinman for clarification?

**Comment by scottkleinman** [comment]
Strange. It works for me now. It must have been a blip or some other nearby error that caused it to fail validation. Thanks for checking, Sharon. I'm glad you found the bug in `entities.dtd` so it wasn't a complete waste of your time.
